name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        rev: [v0.11.0]
        include:
          - os: ubuntu-22.04
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Prepare
        run: |
          ${{ matrix.install-rg }}
          rg --version

          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
          git clone --depth 1 -b master https://github.com/nvim-lua/plenary.nvim ../nvim-treesitter

      - name: Run tests
        run: |
          nvim --version
          make test
